report.pdf: report.tex cherubino.jpg
	xelatex -shell-escape -pdf report.tex
	xelatex -shell-escape -pdf report.tex
	rm report.aux
	rm report.log
	rm report.fdb_latexmk
	rm report.fls
	rm report.toc
	rm report.out
	rm -rf _minted-report
